// <auto-generated />
using System;
using AgendaContatosMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaContatosMVC.Migrations
{
    [DbContext(typeof(AgendaContatosMVCContext))]
    [Migration("20220118032505_Foreignkey2")]
    partial class Foreignkey2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgendaContatosMVC.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DataNascmento");

                    b.Property<string>("Name");

                    b.Property<string>("Rg");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("AgendaContatosMVC.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactId");

                    b.Property<string>("Enderecos");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("AgendaContatosMVC.Models.Fone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<int>("ContactId");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Fone");
                });

            modelBuilder.Entity("AgendaContatosMVC.Models.Endereco", b =>
                {
                    b.HasOne("AgendaContatosMVC.Models.Contact", "Contact")
                        .WithMany("Enderecos")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgendaContatosMVC.Models.Fone", b =>
                {
                    b.HasOne("AgendaContatosMVC.Models.Contact", "Contact")
                        .WithMany("Fones")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
